"""
tests/test_ancestry_convert.py

Тесты Этапа 0 — приведения сырого экспорта AncestryDNA к оформлению
23andMe v3 (core/ancestry_convert.py) и того, что адаптер читает
результат конвертации ровно так же, как читал бы сырой файл.
"""
from __future__ import annotations

from pathlib import Path

import pytest

import main as pipeline
from adapters.ancestry_v2 import (
    LAYOUT_CONVERTED,
    LAYOUT_RAW,
    _find_header,
    parse_ancestry_v2,
)
from core.ancestry_convert import (
    AncestryConvertError,
    convert_ancestry_to_23andme_v3,
    detect_layout,
    prepare_ancestry_file,
)


RAW_HEADER = "\n".join(
    ["#AncestryDNA raw data download"]
    + [f"#comment {i}" for i in range(17)]
    + ["rsid\tchromosome\tposition\tallele1\tallele2"]
)

TEMPLATE_HEADER = (
    "# This data file generated by 23andMe at: \n"
    "#\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
)


def _raw(tmp_path: Path, rows: str, name: str = "AncestryDNA.txt") -> Path:
    path = tmp_path / name
    # CRLF — как в настоящих файлах Ancestry.
    #
    # newline="" здесь обязателен: без него текстовый режим на Windows
    # переводит каждый '\n' в '\r\n', и записанные нами '\r\n'
    # превращаются в '\r\r\n'. Файл после этого читается как удвоенное
    # число строк (пустая строка после каждой настоящей), и индекс
    # строки заголовка уезжает: 18 -> 36. На Linux этого не видно —
    # перевода нет, поэтому тест зелёный там и красный на Windows.
    path.write_text((RAW_HEADER + "\n" + rows).replace("\n", "\r\n"),
                    encoding="utf-8", newline="")
    return path


def _template(tmp_path: Path) -> Path:
    path = tmp_path / "template_v3.txt"
    path.write_text(TEMPLATE_HEADER + "rs1\t1\t100\tAA\n", encoding="utf-8")
    return path


def _data_lines(path: Path) -> list[list[str]]:
    return [
        line.split("\t")
        for line in path.read_text(encoding="utf-8").splitlines()
        if line and not line.startswith("#")
    ]


class _StubReference:
    """Отдаёт первый аллель самой строки как референсное основание —
    так разрешение ориентации не отбраковывает тестовые данные."""

    def __init__(self, bases: dict[tuple[str, int], str]):
        self._bases = bases

    def base_at(self, chrom: str, pos: int) -> str:
        return self._bases.get((chrom, pos), "A")


def _reference_from_raw(path: Path) -> _StubReference:
    from adapters.ancestry_v2 import _normalize_chrom
    bases = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or line.startswith("rsid\t"):
            continue
        parts = line.split("\t")
        if len(parts) == 5 and parts[3] in "ACGT":
            bases[(_normalize_chrom(parts[1]), int(parts[2]))] = parts[3]
    return _StubReference(bases)


# ---------------------------------------------------------------------------
# Оформление результата
# ---------------------------------------------------------------------------
def test_output_has_v3_layout(tmp_path):
    src = _raw(tmp_path, "rs1\t1\t100\tA\tG\nrs2\t1\t200\tC\tC\n")
    dst = tmp_path / "out.txt"
    convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))

    blob = dst.read_bytes()
    assert b"\r\n" not in blob, "v3 — это LF, а не CRLF"
    assert blob.startswith(b"# This data file generated by 23andMe at:")
    assert b"# rsid\tchromosome\tposition\tgenotype\n" in blob

    rows = _data_lines(dst)
    assert all(len(r) == 4 for r in rows), "в v3 ровно четыре колонки"
    assert rows[0] == ["rs1", "1", "100", "AG"]


def test_zero_allele_becomes_double_dash(tmp_path):
    src = _raw(tmp_path, "rs1\t1\t100\t0\t0\n")
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert _data_lines(dst)[0][3] == "--"
    assert stats.no_call == 1


def test_chrom_codes_become_letters(tmp_path):
    src = _raw(tmp_path, "rs_x\t23\t100\tA\tG\nrs_y\t24\t100\tT\tT\nrs_mt\t26\t100\tC\tC\n")
    dst = tmp_path / "out.txt"
    convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert [r[1] for r in _data_lines(dst)] == ["X", "Y", "MT"]


def test_par_merged_into_x_and_resorted(tmp_path):
    """
    У Ancestry PAR (код 25) идёт ПОСЛЕ Y. После слияния с X он обязан
    встать на своё место внутри X, иначе файл перестаёт быть
    отсортированным по (хромосома, позиция).
    """
    src = _raw(tmp_path, (
        "rs_x2\t23\t900\tA\tG\n"
        "rs_y\t24\t100\tT\tT\n"
        "rs_par\t25\t50\tC\tC\n"
    ))
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))

    assert stats.par_merged_into_x == 1
    rows = _data_lines(dst)
    assert [(r[1], int(r[2])) for r in rows] == [("X", 50), ("X", 900), ("Y", 100)]


# ---------------------------------------------------------------------------
# Гаплоидные контиги
# ---------------------------------------------------------------------------
def test_mt_written_as_single_letter(tmp_path):
    src = _raw(tmp_path, "rs_mt\t26\t100\tC\tC\nrs_auto\t1\t100\tC\tC\n")
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    by_rsid = {r[0]: r[3] for r in _data_lines(dst)}
    assert by_rsid["rs_mt"] == "C", "MT в 23andMe пишется одной буквой"
    assert by_rsid["rs_auto"] == "CC", "аутосома остаётся двумя"
    assert stats.haploid_single_letter == 1


def test_female_x_stays_diploid(tmp_path):
    rows = "".join(f"rs_x{i}\t23\t{100 + i}\tA\tG\n" for i in range(10))
    src = _raw(tmp_path, rows)
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert not stats.male
    assert all(len(r[3]) == 2 for r in _data_lines(dst))


def test_male_x_collapsed_to_single_letter(tmp_path):
    rows = "".join(f"rs_x{i}\t23\t{100 + i}\tA\tA\n" for i in range(10))
    src = _raw(tmp_path, rows)
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert stats.male
    assert all(r[3] == "A" for r in _data_lines(dst))


# ---------------------------------------------------------------------------
# Определение формата и идемпотентность
# ---------------------------------------------------------------------------
def test_detect_layout(tmp_path):
    src = _raw(tmp_path, "rs1\t1\t100\tA\tG\n")
    dst = tmp_path / "out.txt"
    convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert detect_layout(src) == "ancestry"
    assert detect_layout(dst) == "23andme"


def test_prepare_skips_already_converted_file(tmp_path):
    """
    Пользователь вполне может выбрать источник «AncestryDNA» и подсунуть
    результат прошлого запуска — переконвертировать его нечем, пяти
    колонок там уже нет.
    """
    src = _raw(tmp_path, "rs1\t1\t100\tA\tG\n")
    converted = tmp_path / "converted.txt"
    convert_ancestry_to_23andme_v3(src, converted, template_path=_template(tmp_path))

    stats = prepare_ancestry_file(converted, tmp_path / "run")
    assert stats.skipped
    assert stats.out_path == converted


def test_prepare_rejects_foreign_format(tmp_path):
    path = tmp_path / "ftdna.csv"
    path.write_text("RSID,CHROMOSOME,POSITION,RESULT\nrs1,1,100,AA\n", encoding="utf-8")
    with pytest.raises(AncestryConvertError):
        prepare_ancestry_file(path, tmp_path / "run")


# ---------------------------------------------------------------------------
# Адаптер читает оба оформления одинаково
# ---------------------------------------------------------------------------
_MIXED_ROWS = (
    "rs_a1\t1\t100\tA\tG\n"
    "rs_a2\t1\t200\tC\tC\n"
    "rs_a3\t2\t300\tT\tT\n"
    "rs_miss\t2\t400\t0\t0\n"
    "rs_mt\t26\t500\tG\tG\n"
    "rs_par\t25\t600\tC\tC\n"
)


def _parse_both(tmp_path, rows):
    src = _raw(tmp_path, rows)
    dst = tmp_path / "converted.txt"
    convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    reference = _reference_from_raw(src)
    return src, dst, parse_ancestry_v2(src, reference), parse_ancestry_v2(dst, reference)


def test_layouts_are_recognised_by_adapter(tmp_path):
    src, dst, _, _ = _parse_both(tmp_path, _MIXED_ROWS)
    assert _find_header(src)[1] == LAYOUT_RAW
    assert _find_header(dst)[1] == LAYOUT_CONVERTED


def test_raw_and_converted_give_identical_result(tmp_path):
    """
    Главная гарантия Этапа 0: конвертация ничего не теряет и ничего не
    меняет. Если сигнатуры разойдутся — разойдётся и кэш доноров.
    """
    _src, _dst, from_raw, from_converted = _parse_both(tmp_path, _MIXED_ROWS)

    assert from_raw.chip_signature == from_converted.chip_signature
    assert from_raw.chip_signature_broad == from_converted.chip_signature_broad
    assert from_raw.total_measured == from_converted.total_measured
    assert from_raw.missing == from_converted.missing

    # Сравнение по содержимому, а не по порядку: у сырого файла PAR (код
    # 25) идёт ПОСЛЕ Y и MT, а конвертер пересортировывает строки, слив
    # PAR с X. Порядок вариантов ни на что не влияет — build_vcf() всё
    # равно сортирует их сам (core/pure_python_core.py::build_vcf,
    # key=(_chrom_sort_key(chrom), pos)); важно, что набор совпадает.
    def _content(result):
        return sorted(
            (v.rsid, v.chrom, v.pos, v.ref, v.alt, v.gt) for v in result.variants
        )

    assert _content(from_raw) == _content(from_converted)


def test_haploid_single_letter_not_lost(tmp_path):
    """
    Регрессия: односимвольный генотип MT ('G' вместо 'GG') не должен
    уходить в invalid_codes. Именно на этом гибкий parse_myheritage_v5()
    молча потерял бы 259 позиций MT/Y реального файла.
    """
    _src, _dst, from_raw, from_converted = _parse_both(tmp_path, _MIXED_ROWS)
    assert from_converted.invalid_codes == 0
    assert "MT" in {v.chrom for v in from_converted.variants}
    assert {v.chrom for v in from_raw.variants} == {v.chrom for v in from_converted.variants}


def test_male_haploid_x_round_trip(tmp_path):
    """То же самое для X мужского образца — там одной буквой пишется вся X."""
    rows = "".join(f"rs_x{i}\t23\t{100 + i}\tA\tA\n" for i in range(10))
    _src, _dst, from_raw, from_converted = _parse_both(tmp_path, rows)
    assert from_converted.invalid_codes == 0
    assert from_raw.chip_signature == from_converted.chip_signature


# ---------------------------------------------------------------------------
# Подключение Этапа 0 к пайплайну
# ---------------------------------------------------------------------------
def test_prepare_source_file_is_noop_for_other_sources(tmp_path):
    path = tmp_path / "ftdna.csv"
    path.write_text("RSID,CHROMOSOME,POSITION,RESULT\nrs1,1,100,AA\n", encoding="utf-8")
    out, stats = pipeline.prepare_source_file("ftdna", path, tmp_path / "run")
    assert out == path
    assert stats is None
    assert not (tmp_path / "run").exists(), "для чужих источников папка даже не создаётся"


def test_prepare_source_file_converts_ancestry(tmp_path):
    src = _raw(tmp_path, "rs1\t1\t100\tA\tG\n")
    run_dir = tmp_path / "run"
    out, stats = pipeline.prepare_source_file(
        "ancestry", src, run_dir, template_path=_template(tmp_path),
    )
    assert out.parent == run_dir, "конвертированный файл кладётся в папку запуска"
    assert out.name.endswith("_23andme_v3.txt")
    assert stats is not None and not stats.skipped
    assert detect_layout(out) == "23andme"


def test_ancestry_listed_as_needing_conversion():
    assert "ancestry" in pipeline._SOURCES_NEEDING_CONVERSION
    assert "ftdna" not in pipeline._SOURCES_NEEDING_CONVERSION


def test_column_header_line_is_not_counted_as_malformed(tmp_path):
    """
    Регрессия: строку названий колонок сырого Ancestry не отличить от
    строки данных по количеству полей (в обеих пять, ведущего '#' нет).
    Конвертер обязан пропускать всё до заголовка включительно, иначе
    считает собственный заголовок испорченной строкой.
    """
    src = _raw(tmp_path, "rs1\t1\t100\tA\tG\nrs2\t1\t200\tC\tC\n")
    dst = tmp_path / "out.txt"
    stats = convert_ancestry_to_23andme_v3(src, dst, template_path=_template(tmp_path))
    assert stats.malformed_rows == 0
    assert stats.rows == 2
